version: '3.8'

services:
  witness:
    build:
      context: ./
      dockerfile: ./docker/witness.dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - 8001:8001
    restart: on-failure
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend.dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - 8003:8003
    restart: on-failure
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy.dockerfile
    depends_on:
      - witness
      - backend
    ports:
      - 8002:8080
    restart: on-failure